[project]
name = "quasar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "asyncio>=4.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
